### ISSUE TITLE
Fails on catkin_make

### ISSUE THREAD

**Issue by nick-zanobini** [Interbotix/phantomx_pincher_arm#1]
`In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp: In function ‘double ikfast_kinematics_plugin::IKatan2(double, double)’:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:193:17: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if( isnan(fy) ) {
                 ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:193:17: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:194:32: error: call of overloaded ‘isnan(double&)’ is ambiguous
         IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
                                ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:49:34: note: in definition of macro ‘IKFAST_ASSERT’
 #define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }
                                  ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:194:32: note: candidates are:
         IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
                                ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:49:34: note: in definition of macro ‘IKFAST_ASSERT’
 #define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }
                                  ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:197:22: error: call of overloaded ‘isnan(double&)’ is ambiguous
     else if( isnan(fx) ) {
                      ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:197:22: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp: In member function ‘bool ikfast_kinematics_plugin::IKSolver::ComputeIk(const IkReal*, const IkReal*, const IkReal*, ikfast_kinematics_plugin::ikfast::IkSolutionListBase<double>&)’:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:485:27: error: call of overloaded ‘isnan(ikfast_kinematics_plugin::IkReal&)’ is ambiguous
 else if( isnan(sj4array[0]) )
                           ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:485:27: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:551:27: error: call of overloaded ‘isnan(ikfast_kinematics_plugin::IkReal&)’ is ambiguous
 else if( isnan(cj3array[0]) )
                           ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:551:27: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:761:27: error: call of overloaded ‘isnan(ikfast_kinematics_plugin::IkReal&)’ is ambiguous
 else if( isnan(cj3array[0]) )
                           ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:761:27: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp: In instantiation of ‘ikfast_kinematics_plugin::CheckValue<T> ikfast_kinematics_plugin::IKatan2WithCheck(T, T, T) [with T = double]’:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:379:96:   required from here
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:216:32: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if( !isnan(fy) && !isnan(fx) ) {
                                ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:216:32: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
In file included from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:216:18: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if( !isnan(fy) && !isnan(fx) ) {
                  ^
/home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:216:18: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/viki/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
make[2]: *** [phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/CMakeFiles/phantomx_pincher_arm_moveit_ikfast_kinematics_plugin.dir/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp.o] Error 1
make[1]: *** [phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/CMakeFiles/phantomx_pincher_arm_moveit_ikfast_kinematics_plugin.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed`

**Comment by ARLunan** [comment]
I encountered simililar catkin_make compile error messages related to the "phantomx_pincher_arm_ikfast_moveit_plugin.cpp" file on UB 14.04/ROS Indigo. Moveit and Setup Assistant appear to be correctly installed as I can run the Setup Assistant tutorial.

First error message and lst summary lines:

In file included from /home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:62:0:
/home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp: In function ‘double ikfast_kinematics_plugin::IKatan2(double, double)’:
/home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:193:17: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if( isnan(fy) ) {
                 ^
/home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_solver.cpp:193:17: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /opt/ros/indigo/include/ros/platform.h:53,
                 from /opt/ros/indigo/include/ros/time.h:53,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /opt/ros/indigo/include/ros/time.h:55:0,
                 from /opt/ros/indigo/include/ros/ros.h:38,
                 from /home/ross/catkin_ws/src/phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp:48:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
SEVERAL MORE SETS of ERROR MESSAGES

make[2]: *** [phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/CMakeFiles/phantomx_pincher_arm_moveit_ikfast_kinematics_plugin.dir/src/phantomx_pincher_arm_ikfast_moveit_plugin.cpp.o] Error 1
make[1]: *** [phantomx_pincher_arm/phantomx_pincher_arm_ikfast_plugin/CMakeFiles/phantomx_pincher_arm_moveit_ikfast_kinematics_plugin.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by wadecore** [comment]
Have you tried compiling in ROS Kinetic? This software is not tested in Indigo.

**Comment by ARLunan** [comment]
Tried a compile in my Ros Kinetic configured recently for my Turtlebot3) with the error below:
I note there seems to be no arbotix packages installed and there don't seem to be any kinetic arbotix packages in Github or the repositories.

 ==> add_subdirectory(phantomx_pincher_arm/phantomx_pincher_arm_bringup)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "arbotix_python"
  with any of the following names:

    arbotix_pythonConfig.cmake
    arbotix_python-config.cmake

  Add the installation prefix of "arbotix_python" to CMAKE_PREFIX_PATH or set
  "arbotix_python_DIR" to a directory containing one of the above files.  If
  "arbotix_python" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  phantomx_pincher_arm/phantomx_pincher_arm_bringup/CMakeLists.txt:4 (find_package)

**Comment by Sandunika97** [comment]
Could not find a package configuration file provided by "arbotix_python"
  with any of the following names:

    arbotix_pythonConfig.cmake
    arbotix_python-config.cmake

I'm getting a similar error. Does anyone know a answer for this?
