### ISSUE TITLE
Readme: MK3 or MK2?

### ISSUE THREAD

**Issue by bgilreath** [Interbotix/phantomx_pincher_arm#4]
The readme says this is for: ROS Package for the PhantomX Pincher MK3 Arm. The Trossen Robotics website only has a MK2 arm: https://www.trossenrobotics.com/p/PhantomX-Pincher-Robot-Arm.aspx - which is the assumption that they should match.

Is this library ahead of the hardware or for the MK2 hardware?

**Comment by swinterbotix** [comment]
@bgilreath,

Currently, we only sell the PhantomX Pincher MK2 as a Desktop version. However, the PhantomX Pincher MK3 arm is still the one installed on the Turtlebot2i. There were plans to create a Desktop PhantomX Pincher MK3 arm, but it never happened.
